### ISSUE TITLE
刷新recyclerview列表数据由不满屏到满屏出现crash

### ISSUE THREAD

**Issue by MrXiong** [pengjianbo/LoadingViewFinal#15]
Process: com.jgw.supercodepda, PID: 1813
                                                                    java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true
                                                                        at android.support.v7.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:4878)
                                                                        at android.support.v7.widget.RecyclerView$Recycler.quickRecycleScrapView(RecyclerView.java:4951)
                                                                        at android.support.v7.widget.RecyclerView$LayoutManager.removeAndRecycleScrapInt(RecyclerView.java:7352)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3101)
                                                                        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:2917)
                                                                        at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3283)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                                        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                                        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                                        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                                        at android.view.View.layout(View.java:14834)
                                                                        at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                                        at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:1983)
                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1740)
                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:996)
                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5600)
                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:574)
                                                                        at android.view.Choreographer.doFrame(Choreographer.java:544)
                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
                                                                    	at android.os.Handler.handleCallback(Handler.

**Comment by MrXiong** [comment]
问题解决了，是我数据的原因
